### ISSUE TITLE
testing file?

### ISSUE THREAD

**Issue by sunjunlishi** [jordi-adell/dspone#2]
could you supply it?

speech/rh2filter.fir

**Comment by jordi-adell** [comment]
I cannot not. I am sorry. In fact this test is disabled. Anyway, the fir file should be a sequence of floats one per line. These floats must be the coefficients of a FIR filter.

**Comment by jordi-adell** [comment]
You can create your own fir file.

**Comment by sunjunlishi** [comment]
I suddenly lost my head ,sorry
